server:
  port: 8080
  servlet:
    context-path: /data-manipulation

spring:
  sql:
    init:
      mode: never
      platform: default
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:default-pw}

mybatis:
    mapper-locations: classpath*:mybatis/*.xml
    configuration:
      map-underscore-to-camel-case: true
    configuration-properties:
      dbschema: datamanipulation

jwt:
  public:
    key: classpath:jwt_pkcs8_pem_public.key
  private:
    key: classpath:jwt_pkcs8_pem.key